/**
* @description       :
* @author            : mmadridp@omegacrmconsulting.com
* @group             :
* @last modified on  : 13-03-2024
* @last modified by  : mmadridp@omegacrmconsulting.com
**/
public with sharing class OM_VID_Constants {
    public static String opportunityStatusQuotation {get{return 'Quotation';}} 
    public static String opportunityRTFifty {get{return 'Fifty_Master_Opportunity';}}
    public static String quoteRTFifty {get{return 'OM_VID_Quote_Fifty';}}
    public static final String quoteName {get{return 'Quote';}}  
    public static final String oppName {get{return 'Opportunity';}}
    public static final String fiftyTemplateName {get{return '_Email_de_Oferta';}}
    
    public static final String errorContentVersion {get{return 'No existe un documento de Oferta asociado que poder enviar';}}
    public static final String errorContentVersion {get{return 'No existe un documento de Oferta asociado que poder enviar';}} 
}